### PR TITLE
adding case sensitive var

### PR DESCRIPTION
**Pull request by blastik**
can we get that added?

### CODE REVIEW

**Comment by lgallard** [comment]
@blastik thanks! 

Merged and released!

**Comment by blastik** [comment]
@lgallard wow so fast. i was going to update readme sorry! will do that in a separate pr

**Comment by lgallard** [comment]
@blastik I already did it. Thanks!!

**Comment by lgallard** [comment]
@blastik tag 0.3.2 has the update (and merged to master)

**Pull request merged**
